# Generated by Django 4.1.6 on 2023-02-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('psswd', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
