# Generated by Django 4.1.6 on 2023-02-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_members_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
