# Generated by Django 4.1.6 on 2023-02-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_leaveform_member_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
