# Generated by Django 4.1.6 on 2023-02-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(default='bench', max_length=20),
        ),
    ]
