# Generated by Django 4.1.6 on 2023-02-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.CharField(max_length=10),
        ),
    ]
