# Generated by Django 4.1.6 on 2023-02-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='name',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
    ]
