# Generated by Django 4.1.6 on 2023-02-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0009_remove_leaveform_email_remove_leaveform_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="age",
        ),
        migrations.RemoveField(
            model_name="member",
            name="psswd",
        ),
        migrations.AddField(
            model_name="member",
            name="DOB",
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="department",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="designation",
            field=models.CharField(default="Employee", max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="doj",
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=10),
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="fname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="lname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
