# Generated by Django 4.1.6 on 2023-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_leaveform_email_remove_leaveform_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
