# Generated by Django 4.1.6 on 2023-02-12 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0010_remove_member_age_remove_member_psswd_member_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveform",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
