# Generated by Django 4.1.6 on 2023-02-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_leaveform_employee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
