# Generated by Django 4.1.6 on 2023-02-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='status',
            field=models.CharField(default='applied', max_length=100),
        ),
    ]
