# Generated by Django 4.1.6 on 2023-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='status',
            field=models.CharField(default='applied', max_length=10),
        ),
    ]
