# Generated by Django 4.1.6 on 2023-02-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_leaveform_days_alter_leaveform_end_date_and_more'),
        ('myapp', '0013_leaveform_status'),
    ]

    operations = [
    ]
