# Generated by Django 4.1.6 on 2023-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20230212_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='days',
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
