# Generated by Django 4.1.6 on 2023-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_leaveform_days_alter_leaveform_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='start_date',
            field=models.DateField(),
        ),
    ]
