# Generated by Django 4.1.6 on 2023-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_leaveform_days_alter_leaveform_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='leave_balance',
            field=models.IntegerField(default=30),
        ),
    ]
